[build]
  base = "apps/agenda"
  command = "cd ../.. && npx turbo run build --filter=agenda"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"
